// Email + Telegram notification utility for trade alerts

import { sendTelegramMessage, formatTradeEntry, formatTradeExit, formatDailyPnl, formatRiskAlert } from '@/lib/telegram';
import { prisma } from '@/lib/db';

const NOTIFICATION_API = 'https://apps.abacus.ai/api/sendNotificationEmail';

function getAppName(): string {
  try {
    const url = process.env.NEXTAUTH_URL ?? '';
    return url ? new URL(url).hostname.split('.')[0] : 'NexusQuant';
  } catch {
    return 'NexusQuant';
  }
}

function getSenderEmail(): string {
  try {
    const url = process.env.NEXTAUTH_URL ?? '';
    return url ? `noreply@${new URL(url).hostname}` : 'noreply@mail.abacusai.app';
  } catch {
    return 'noreply@mail.abacusai.app';
  }
}

async function sendEmail(notificationId: string, subject: string, htmlBody: string, recipientEmail?: string): Promise<boolean> {
  try {
    const res = await fetch(NOTIFICATION_API, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        deployment_token: process.env.ABACUSAI_API_KEY,
        app_id: process.env.WEB_APP_ID,
        notification_id: notificationId,
        subject,
        body: htmlBody,
        is_html: true,
        recipient_email: recipientEmail ?? 'narendhrareddi@gmail.com',
        sender_email: getSenderEmail(),
        sender_alias: 'NexusQuant Trading Bot',
      }),
    });
    const result = await res.json();
    if (result?.notification_disabled) {
      console.log('Notification disabled by user, skipping');
      return true;
    }
    return result?.success ?? false;
  } catch (err: any) {
    console.error('Email notification error:', err?.message);
    return false;
  }
}

export async function sendTradeEntryAlert(trade: {
  symbol: string;
  direction: string;
  quantity: number;
  entryPrice: number;
  stopLoss: number;
  target: number;
  strategy: string;
}): Promise<void> {
  const notifId = process.env.NOTIF_ID_TRADE_ENTRY_ALERT;
  if (!notifId) return;

  const color = trade.direction === 'BUY' ? '#10B981' : '#EF4444';
  const html = `
    <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: 0 auto; background: #0f172a; color: #e2e8f0; padding: 24px; border-radius: 12px;">
      <div style="text-align: center; margin-bottom: 20px;">
        <h2 style="color: ${color}; margin: 0;">🤖 Trade ${trade.direction === 'BUY' ? 'Entry' : 'Short'} Alert</h2>
        <p style="color: #94a3b8; font-size: 13px;">NexusQuant Autonomous Trading</p>
      </div>
      <div style="background: #1e293b; padding: 20px; border-radius: 8px; border-left: 4px solid ${color};">
        <table style="width: 100%; border-collapse: collapse;">
          <tr><td style="padding: 8px 0; color: #94a3b8;">Symbol</td><td style="padding: 8px 0; font-weight: bold; text-align: right;">${trade.symbol}</td></tr>
          <tr><td style="padding: 8px 0; color: #94a3b8;">Direction</td><td style="padding: 8px 0; font-weight: bold; text-align: right; color: ${color};">${trade.direction}</td></tr>
          <tr><td style="padding: 8px 0; color: #94a3b8;">Quantity</td><td style="padding: 8px 0; font-weight: bold; text-align: right;">${trade.quantity}</td></tr>
          <tr><td style="padding: 8px 0; color: #94a3b8;">Entry Price</td><td style="padding: 8px 0; font-weight: bold; text-align: right;">₹${trade.entryPrice.toFixed(2)}</td></tr>
          <tr><td style="padding: 8px 0; color: #94a3b8;">Stop Loss</td><td style="padding: 8px 0; font-weight: bold; text-align: right; color: #EF4444;">₹${trade.stopLoss.toFixed(2)}</td></tr>
          <tr><td style="padding: 8px 0; color: #94a3b8;">Target</td><td style="padding: 8px 0; font-weight: bold; text-align: right; color: #10B981;">₹${trade.target.toFixed(2)}</td></tr>
          <tr><td style="padding: 8px 0; color: #94a3b8;">Strategy</td><td style="padding: 8px 0; font-weight: bold; text-align: right;">${trade.strategy}</td></tr>
        </table>
      </div>
      <p style="color: #64748b; font-size: 11px; text-align: center; margin-top: 16px;">Auto-generated by NexusQuant at ${new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })}</p>
    </div>`;

  await sendEmail(notifId, `🤖 ${trade.direction} ${trade.symbol} @ ₹${trade.entryPrice.toFixed(2)}`, html);

  // Telegram
  await sendTelegramToAllEnabled(formatTradeEntry({
    action: trade.direction,
    symbol: trade.symbol,
    strategy: trade.strategy,
    price: trade.entryPrice,
    confidence: 0.8,
  }));
}

export async function sendTradeExitAlert(trade: {
  symbol: string;
  direction: string;
  entryPrice: number;
  exitPrice: number;
  quantity: number;
  pnl: number;
  reason: string;
}): Promise<void> {
  const notifId = process.env.NOTIF_ID_TRADE_EXIT_ALERT;
  if (!notifId) return;

  const pnlColor = trade.pnl >= 0 ? '#10B981' : '#EF4444';
  const pnlEmoji = trade.pnl >= 0 ? '💰' : '📉';
  const html = `
    <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: 0 auto; background: #0f172a; color: #e2e8f0; padding: 24px; border-radius: 12px;">
      <div style="text-align: center; margin-bottom: 20px;">
        <h2 style="color: ${pnlColor}; margin: 0;">${pnlEmoji} Trade Closed</h2>
        <p style="color: #94a3b8; font-size: 13px;">P&L: <span style="color: ${pnlColor}; font-weight: bold;">₹${trade.pnl.toFixed(2)}</span></p>
      </div>
      <div style="background: #1e293b; padding: 20px; border-radius: 8px; border-left: 4px solid ${pnlColor};">
        <table style="width: 100%; border-collapse: collapse;">
          <tr><td style="padding: 8px 0; color: #94a3b8;">Symbol</td><td style="padding: 8px 0; font-weight: bold; text-align: right;">${trade.symbol}</td></tr>
          <tr><td style="padding: 8px 0; color: #94a3b8;">Entry</td><td style="padding: 8px 0; text-align: right;">₹${trade.entryPrice.toFixed(2)}</td></tr>
          <tr><td style="padding: 8px 0; color: #94a3b8;">Exit</td><td style="padding: 8px 0; text-align: right;">₹${trade.exitPrice.toFixed(2)}</td></tr>
          <tr><td style="padding: 8px 0; color: #94a3b8;">Qty</td><td style="padding: 8px 0; text-align: right;">${trade.quantity}</td></tr>
          <tr><td style="padding: 8px 0; color: #94a3b8;">P&L</td><td style="padding: 8px 0; font-weight: bold; text-align: right; color: ${pnlColor};">₹${trade.pnl.toFixed(2)}</td></tr>
          <tr><td style="padding: 8px 0; color: #94a3b8;">Exit Reason</td><td style="padding: 8px 0; text-align: right;">${trade.reason}</td></tr>
        </table>
      </div>
      <p style="color: #64748b; font-size: 11px; text-align: center; margin-top: 16px;">Auto-generated by NexusQuant at ${new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })}</p>
    </div>`;

  await sendEmail(notifId, `${pnlEmoji} ${trade.symbol} Closed: ₹${trade.pnl.toFixed(2)}`, html);

  // Telegram
  await sendTelegramToAllEnabled(formatTradeExit(trade));
}

export async function sendDailyPnlSummary(summary: {
  totalPnl: number;
  tradesCount: number;
  winCount: number;
  lossCount: number;
  trades: { symbol: string; pnl: number; strategy: string }[];
}): Promise<void> {
  const notifId = process.env.NOTIF_ID_DAILY_PL_SUMMARY;
  if (!notifId) return;

  const pnlColor = summary.totalPnl >= 0 ? '#10B981' : '#EF4444';
  const winRate = summary.tradesCount > 0 ? ((summary.winCount / summary.tradesCount) * 100).toFixed(1) : '0';
  
  const tradeRows = summary.trades?.map?.((t) => {
    const c = t.pnl >= 0 ? '#10B981' : '#EF4444';
    return `<tr><td style="padding: 6px 8px; border-bottom: 1px solid #334155;">${t.symbol}</td><td style="padding: 6px 8px; border-bottom: 1px solid #334155; color: ${c}; text-align: right;">₹${t.pnl.toFixed(2)}</td><td style="padding: 6px 8px; border-bottom: 1px solid #334155; text-align: right;">${t.strategy}</td></tr>`;
  })?.join?.('') ?? '';

  const html = `
    <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: 0 auto; background: #0f172a; color: #e2e8f0; padding: 24px; border-radius: 12px;">
      <div style="text-align: center; margin-bottom: 20px;">
        <h2 style="color: #e2e8f0; margin: 0;">📊 Daily Trading Summary</h2>
        <p style="color: #94a3b8; font-size: 13px;">${new Date().toLocaleDateString('en-IN', { timeZone: 'Asia/Kolkata', weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</p>
      </div>
      <div style="background: #1e293b; padding: 20px; border-radius: 8px; text-align: center; margin-bottom: 16px;">
        <p style="color: #94a3b8; margin: 0 0 8px;">Net P&L</p>
        <p style="color: ${pnlColor}; font-size: 32px; font-weight: bold; margin: 0;">₹${summary.totalPnl.toFixed(2)}</p>
      </div>
      <div style="display: flex; gap: 12px; margin-bottom: 16px;">
        <div style="flex: 1; background: #1e293b; padding: 16px; border-radius: 8px; text-align: center;">
          <p style="color: #94a3b8; margin: 0; font-size: 12px;">Trades</p>
          <p style="font-size: 20px; font-weight: bold; margin: 4px 0 0;">${summary.tradesCount}</p>
        </div>
        <div style="flex: 1; background: #1e293b; padding: 16px; border-radius: 8px; text-align: center;">
          <p style="color: #94a3b8; margin: 0; font-size: 12px;">Win Rate</p>
          <p style="font-size: 20px; font-weight: bold; margin: 4px 0 0; color: #10B981;">${winRate}%</p>
        </div>
        <div style="flex: 1; background: #1e293b; padding: 16px; border-radius: 8px; text-align: center;">
          <p style="color: #94a3b8; margin: 0; font-size: 12px;">W / L</p>
          <p style="font-size: 20px; font-weight: bold; margin: 4px 0 0;"><span style="color: #10B981;">${summary.winCount}</span> / <span style="color: #EF4444;">${summary.lossCount}</span></p>
        </div>
      </div>
      ${tradeRows ? `<div style="background: #1e293b; border-radius: 8px; overflow: hidden;"><table style="width: 100%; border-collapse: collapse;"><thead><tr style="background: #334155;"><th style="padding: 8px; text-align: left; color: #94a3b8; font-size: 12px;">Symbol</th><th style="padding: 8px; text-align: right; color: #94a3b8; font-size: 12px;">P&L</th><th style="padding: 8px; text-align: right; color: #94a3b8; font-size: 12px;">Strategy</th></tr></thead><tbody>${tradeRows}</tbody></table></div>` : ''}
      <p style="color: #64748b; font-size: 11px; text-align: center; margin-top: 16px;">Auto-generated by NexusQuant</p>
    </div>`;

  const emoji = summary.totalPnl >= 0 ? '💰' : '📉';
  await sendEmail(notifId, `${emoji} Daily P&L: ₹${summary.totalPnl.toFixed(2)} | ${summary.tradesCount} trades`, html);

  // Telegram
  await sendTelegramToAllEnabled(formatDailyPnl({
    totalPnl: summary.totalPnl,
    totalTrades: summary.tradesCount,
    winRate: summary.tradesCount > 0 ? (summary.winCount / summary.tradesCount) * 100 : 0,
    openPositions: 0,
  }));
}

export async function sendRiskWarning(details: {
  currentLoss: number;
  maxLoss: number;
  message: string;
}): Promise<void> {
  const notifId = process.env.NOTIF_ID_RISK_LIMIT_WARNING;
  if (!notifId) return;

  const pct = Math.min(100, Math.abs(details.currentLoss / details.maxLoss) * 100);
  const html = `
    <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: 0 auto; background: #0f172a; color: #e2e8f0; padding: 24px; border-radius: 12px;">
      <div style="text-align: center; margin-bottom: 20px;">
        <h2 style="color: #EF4444; margin: 0;">⚠️ Risk Limit Warning</h2>
        <p style="color: #94a3b8; font-size: 13px;">Immediate attention required</p>
      </div>
      <div style="background: #1e293b; padding: 20px; border-radius: 8px; border-left: 4px solid #EF4444;">
        <p style="margin: 0 0 12px; font-weight: bold;">${details.message}</p>
        <p style="margin: 0; color: #94a3b8;">Current Loss: <span style="color: #EF4444; font-weight: bold;">₹${Math.abs(details.currentLoss).toFixed(2)}</span> / ₹${details.maxLoss}</p>
        <div style="background: #334155; height: 8px; border-radius: 4px; margin-top: 12px; overflow: hidden;">
          <div style="background: #EF4444; height: 100%; width: ${pct}%; border-radius: 4px;"></div>
        </div>
        <p style="margin: 8px 0 0; color: #94a3b8; font-size: 12px;">${pct.toFixed(0)}% of daily limit used</p>
      </div>
      <p style="color: #64748b; font-size: 11px; text-align: center; margin-top: 16px;">Auto-generated by NexusQuant at ${new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })}</p>
    </div>`;

  await sendEmail(notifId, `⚠️ Risk Alert: ₹${Math.abs(details.currentLoss).toFixed(2)} loss (${pct.toFixed(0)}% of limit)`, html);

  // Telegram
  await sendTelegramToAllEnabled(formatRiskAlert({
    message: details.message,
    dailyLoss: Math.abs(details.currentLoss),
    limit: details.maxLoss,
    action: 'Trading paused',
  }));
}

// Helper: send Telegram to all users with Telegram enabled
async function sendTelegramToAllEnabled(message: string) {
  try {
    const configs = await prisma.tradingConfig.findMany({
      where: { enableTelegram: true, telegramChatId: { not: '' } },
      select: { telegramChatId: true },
    });
    await Promise.allSettled(
      (configs ?? []).map((c: any) => sendTelegramMessage(c?.telegramChatId ?? '', message))
    );
  } catch (err: any) {
    console.error('[Telegram] Broadcast error:', err?.message);
  }
}
